server:
  port: 8085
  servlet:
    context-path: /app

custom:
  email: ${EMAIL}
  password: ${EMAIL_PASSWORD}
  url: ${APPLICATION_URL}

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/template
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    use-root-path: true
  paths-to-match:
    - /**/v1/**/
    - /auth/**
    - /user/**
logging:
  level:
    com:
      application=INFO:
      org.hibernate.SQL: OFF
      org.hibernate.type.descriptor.sql.BasicBinder: OFF